### ISSUE TITLE
twms122

### ISSUE THREAD

**Issue by Riremito** [zhyonc/TMSLauncher#1]
TWMS v122 HS removal code. (sorry if it includes virtualized memory.)
```c
// Remove HS
00564878:
db 31 C0 C3

0081FB58:
db 31 C0 C3

0081FE3D:
db 31 C0 C3
```

how to make TWMS v122.1 LocalHost Client
https://dupeplz.net/forum/index.php?threads/twms-v122-1.173/
this page has ip block, you need to enter "VVV" to register page to see this page.

local host clients
https://mega.nz/folder/LqpTyYCQ#IFo6QLZSEjVCY4BnH-mxJA

**Comment by zhyonc** [comment]
Thanks for sharing the removal code and AobList has followed up now.
